local resource = require("k8s.core.resource")

describe("resource", function()
  describe("capabilities", function()
    it("should return default capabilities (all false)", function()
      local caps = resource.capabilities("Unknown")

      assert.is_false(caps.exec)
      assert.is_false(caps.logs)
      assert.is_false(caps.scale)
      assert.is_false(caps.restart)
      assert.is_false(caps.port_forward)
    end)

    it("should return Pod capabilities", function()
      local caps = resource.capabilities("Pod")

      assert.is_true(caps.exec)
      assert.is_true(caps.logs)
      assert.is_false(caps.scale)
      assert.is_false(caps.restart)
      assert.is_true(caps.port_forward)
    end)

    it("should return Deployment capabilities", function()
      local caps = resource.capabilities("Deployment")

      assert.is_false(caps.exec)
      assert.is_false(caps.logs)
      assert.is_true(caps.scale)
      assert.is_true(caps.restart)
      assert.is_true(caps.port_forward)
    end)

    it("should return Service capabilities", function()
      local caps = resource.capabilities("Service")

      assert.is_false(caps.exec)
      assert.is_false(caps.logs)
      assert.is_false(caps.scale)
      assert.is_false(caps.restart)
      assert.is_true(caps.port_forward)
    end)
  end)
end)
