---@meta
--- kubectl_port.lua - KubectlPort インターフェース定義
--- インフラ層（adapter.lua）が実装するべきインターフェースを LuaCATS で定義

---@class KubectlPort
---@field get_resources fun(kind: string, namespace: string|nil, callback: fun(result: K8sResult))
---@field describe fun(kind: string, name: string, namespace: string|nil, callback: fun(result: K8sResult))
---@field delete fun(kind: string, name: string, namespace: string|nil, callback: fun(result: K8sResult))
---@field scale fun(kind: string, name: string, namespace: string|nil, replicas: number, callback: fun(result: K8sResult))
---@field restart fun(kind: string, name: string, namespace: string|nil, callback: fun(result: K8sResult))
---@field exec fun(pod: string, container: string, namespace: string, shell: string|nil): K8sResult
---@field logs fun(pod: string, container: string, namespace: string, opts: LogOpts): K8sResult
---@field port_forward fun(resource: string, namespace: string, local_port: number, remote_port: number): K8sResult
---@field get_contexts fun(callback: fun(result: K8sResult))
---@field use_context fun(name: string, callback: fun(result: K8sResult))
---@field get_namespaces fun(callback: fun(result: K8sResult))
