local input = require("k8s.ui.components.input")

describe("input", function()
  describe("validate_port", function()
    it("should return true for valid port", function()
      local valid, err = input.validate_port("8080")
      assert.is_true(valid)
      assert.is_nil(err)
    end)

    it("should return false for non-numeric input", function()
      local valid, err = input.validate_port("abc")
      assert.is_false(valid)
      assert.equals("Port must be a number", err)
    end)

    it("should return false for port below 1", function()
      local valid, err = input.validate_port("0")
      assert.is_false(valid)
      assert.equals("Port must be between 1 and 65535", err)
    end)

    it("should return false for port above 65535", function()
      local valid, err = input.validate_port("70000")
      assert.is_false(valid)
      assert.equals("Port must be between 1 and 65535", err)
    end)

    it("should return false for empty string", function()
      local valid, err = input.validate_port("")
      assert.is_false(valid)
      assert.equals("Port must be a number", err)
    end)
  end)

  describe("validate_replicas", function()
    it("should return true for valid replicas", function()
      local valid, err = input.validate_replicas("3")
      assert.is_true(valid)
      assert.is_nil(err)
    end)

    it("should return true for zero replicas", function()
      local valid, err = input.validate_replicas("0")
      assert.is_true(valid)
      assert.is_nil(err)
    end)

    it("should return false for negative replicas", function()
      local valid, err = input.validate_replicas("-1")
      assert.is_false(valid)
      assert.equals("Replicas must be 0 or greater", err)
    end)

    it("should return false for non-numeric input", function()
      local valid, err = input.validate_replicas("abc")
      assert.is_false(valid)
      assert.equals("Replicas must be a number", err)
    end)
  end)
end)
